title: fskintra
description: ForÃ¦ldreIntra ğŸ‘ª tilï¸ e-mail ğŸ“§
show_downloads: false
theme: jekyll-theme-slate
lang: da-DK

menu:
  - title: fskintra
    url: /
  - title: Installation
    url: /install
  - title: Opdatering
    url: /upgrade
  - title: Problemer?
    url: /troubleshooting
  - title: Automatisk kÃ¸rsel
    url: /cron
  - title: Docker
    url: /docker
